#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/Mingzat-Regular.ufo -l source/logs/norm.log

echo "Updating glyph orders in Regular..."
# psfsetglyphorder -q -p checkfix=none -p backup=False --header sort_final --field public.glyphOrder -i source/glyph_data.csv source/*-Regular.ufo

# psfsetglyphorder -q -p checkfix=none -p backup=False --header sort_final -i source/glyph_data.csv source/Mingzat-Regular.ufo

echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n  Mingzat        -i org.sil.fonts source/*-Regular.ufo  -o "source/Mingzat-WOFF-metadata.xml"

echo "Building internal fea..."
makefea -o source/Mingzat-Regular.ufo/features.fea -l source/logs/Mingzat-Regular-makefea.log -i source/opentype/main.feax source/Mingzat-Regular.ufo &
