#!/bin/sh

echo "-----Normalizing other UFOs..."
psfnormalize -p checkfix=fix source/Mingzat-Regular.ufo       &
wait

echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n  Mingzat        -i org.sil.fonts source/*-Regular.ufo  -o "source/Mingzat-WOFF-metadata.xml"

# not currently working
echo "Updating glyph orders in Regular..."
# psfsetglyphorder -q -p checkfix=none -p backup=False --header sort_final,sort_final --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/*-Regular.ufo

echo "Building internal fea..."
makefea -o source/Mingzat-Regular.ufo/features.fea -l source/logs/Mingzat-Regular-makefea.log -i source/opentype/main.feax source/Mingzat-Regular.ufo &
